package symboleTable;

public enum Tag {
    NUM, ID, ID_NAME_PROCEDURE, PROCEDURE, FIN_PROCEDURE, DECLARE,
    EQUALITY_SIGN, LESS_SIGN,  ADDITION_SIGN, MULTIPLICATION_SIGN,
    DIVISION_SIGN, SEMICOLON, TWO_POINTS, ENTIER, REEL, OPENING_PARENTHESIS, CLOSING_PARENTHESIS
}
